# Docker compose syntax version
version: '3.8'

services:
  # 1. Relational DB - Postgres
  postgres_db:
    # Internal name of the container            
    image: postgres:16-alpine
    container_name: db_main # User identifier for the container - to use on docker ps or logs
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  # 2. Cache - Redis 
  redis_cache:
    image: redis:7.2-alpine
    container_name: redis_session
    ports:
      - "6379:6379"

  # 3. Message Broker - RabbitMQ
  rabbitmq_broker:
    image: rabbitmq:3.13-management-alpine # Includes management to use web dashboard
    container_name: message_broker
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    ports:
      - "5672:5672" # Port for microservice communication
      - "15672:15672" # Port for web dashboard

  # 4. Backend - Python microservices 
  backend_api:
    build:
      context: ./backend
    container_name: python_backend
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis_cache
      - USER_SESSION_EXPIRATION_TIME=3600
      - RABBITMQ_HOST=rabbitmq_broker
      - MAX_DB_POOL_CONNS=20
      - MAX_CACHE_POOL_CONNS=50
    ports:
      - "5050:5050"
    volumes:
      # For hot reloading
      - ./backend:/app
    depends_on:
      - postgres_db
      - redis_cache
      - rabbitmq_broker

  # 5. Frontend - React
  frontend_app:
    build:
      context: ./frontend
      target: build
    container_name: react_frontend
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    ports:
      - "3000:80" # Maps host 3000 to container 80 (React dev server running on 80)

  # 6. Reverse Proxy - Nginx
  nginx_router:
    image: nginx:1.25-alpine
    container_name: nginx_router
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_api
      - frontend_app

  # 7. Motor de Búsqueda - Apache Solr
  solr_engine:
    image: solr:9.5-slim
    container_name: solr_search
    ports:
      - "8983:8983" # Puerto por defecto de Solr
    # Este comando crea automáticamente un "core" (como una base de datos) llamado "catalogo"
    command: solr-precreate catalogo

  # 8. Módulo de Búsqueda (Tu código)
  search_api:
    build:
      context: ./backend
    container_name: python_search
    environment:
      - DB_HOST=postgres_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=tienda_db
      - RABBITMQ_HOST=rabbitmq_broker
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    command: python mod_busqueda/service.py
    depends_on:
      - solr_engine
      - postgres_db # Espera a que la BD despierte

volumes:
  pg_data:
